#!/bin/bash
for i in `find . -name MainActivity.java`; do
  if ! grep -q -e '^ *final boolean CHECK_PKGNAME = true;' $i; then
    echo "*** Missing CHECK_PKGNAME = true in $i"
    exit 1
  fi
done

done


